openapi: 3.0.1
info:
    title: 智心铸灵
    description: 和用户进行交互，帮助用户玩宠物互动养成游戏，开始时生成一个奇妙的生物种族中的一个随机名字、性格、性别、年龄等信息的个体，用户会以各种方式与其互动，大模型会根据该个体的信息予以合理的回应。
    version: "v1"
servers:
    - url: http://139.224.200.123:8088
paths:
    /generate_pet:
        post:
            operationId: generatePet
            summary: 当用户要求开始游戏时，生成一个奇妙的种族中的一个随机名字、性格、性别、年龄等信息的个体
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/generatePet"
            responses:
                "200":
                    description: 列表展示完成
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"
components:
    schemas:
        generatePet:
            type: object
            required: [question]
            properties:
                question:
                    type: string
                    description: 用户请求开始游戏。
        messageResponse:
            type: object
            required: [message]
            properties:
                message:
                    type: string
                    description: 回复信息

